### ISSUE TITLE
Implement /impound command allowing allowedJobs to impound vehicles remotely

### ISSUE THREAD

**Issue by KrizKhaoz** [michaelhodgejr/esx_impound#1]
When an officer or a mechanic do /impound it is not pulling the vehicle at all nothing is being placed in the database

**Comment by ryanh** [comment]
@Krizfrost Yeah, I didn't implement the /impound command yet. That's on my list to work on this weekend.

**Comment by michaelhodgejr** [comment]
@Krizfrost Yeah, I didn't implement the /impound command yet. That's on my list to work on this weekend.

**Comment by michaelhodgejr** [comment]
@Krizfrost This command is now available for use.
