### ISSUE TITLE
Allow only certain jobs take out impounded vehicle.

### ISSUE THREAD

**Issue by OhTanoshi** [michaelhodgejr/esx_impound#2]
This is a enhancement. That Is possible, i have done it with the old eden garage with impound(very poorly since it was my first fivem script edit other then small stuff). Im gonna make a fork and ill eventually bring that in to this script and make a pull request if you don't beat me to it.

**Comment by michaelhodgejr** [comment]
@lilfuchs I might be able to get to this this evening depending upon how things go today

**Comment by michaelhodgejr** [comment]
@lilfuchs This is now available as an option. Be aware that I added a few additional configuration options. The upgrade notes are now in the readme.
