### ISSUE TITLE
upgrade the server.lua line.90 to

### ISSUE THREAD

**Issue by shyricaus** [michaelhodgejr/esx_impound#4]
-- Delete vehicle from garage
    MySQL.Async.execute("DELETE FROM owned_vehicles WHERE plate=@plate LIMIT 1", {['@plate'] = vehicle.plate})

**Comment by shyricaus** [comment]
but now the CPU usage is perfect

**Comment by michaelhodgejr** [comment]
@shyricaus That delete statement is using the ID column of the owned vehicles table which is a primary key. There is nothing wrong with using the ID column and in fact it is encouraged to do so. I'm glad your CPU usage problem is fixed though!
