### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by shyricaus** [michaelhodgejr/esx_impound#5]
when I'm trying to learn sometimes the vehicles, it says that I do not have permission even though I'm with the right job.

**Comment by shyricaus** [comment]
is not recognizing the job when it is turned on, only when I switch from police to mechanical or im right to work

**Comment by michaelhodgejr** [comment]
@shyricaus Can you paste your config.lua here so I can take a look?

Also you say that it isn't recognizing when turned on, only when you switch jobs. Are you saying it isn't recognizing the job when you first connect in to your server?

**Comment by shyricaus** [comment]
yes

**Comment by michaelhodgejr** [comment]
@shyricaus I just tried to reproduce this and was unable to do so. I'd suggest making sure you have the latest version. On load it loads the current players job and uses that for permission checks. There is also a hook for when the player changes jobs themselves. 

The one thing to know is that the Blips on the map will not appear when you change jobs. You'll have to log out and back in to see those.

**Comment by shyricaus** [comment]
![image](https://user-images.githubusercontent.com/28937245/45575664-b34c1a80-b84a-11e8-8fad-3ea11cc19f91.png)

**Comment by shyricaus** [comment]
And I'm sweating the last version you passed.
